# Generated by Django 4.0.1 on 2022-02-19 05:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='Store started on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='lastUpdated',
            field=models.DateField(auto_now=True, help_text='Store last updated'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A short title', max_length=80)),
                ('description', models.CharField(blank=True, help_text='Detail about your product', max_length=700)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Selling price including shipping', max_digits=8)),
                ('created', models.DateField(auto_now_add=True, help_text='Product added on')),
                ('lastUpdated', models.DateField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
    ]
