# Generated by Django 4.0.1 on 2022-02-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_created_store_lastupdated_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publish',
            field=models.BooleanField(default=False, help_text='Publish'),
        ),
    ]
