# Generated by Django 4.0.1 on 2022-02-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_store_shop_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop_img',
            field=models.ImageField(blank=True, upload_to='shopImages/'),
        ),
    ]
