# Generated by Django 4.0.1 on 2022-02-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_shop_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shop_img',
        ),
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, upload_to='productImages/'),
        ),
    ]
